#!/bin/sh
set -e

if [ "$1" = "remove" ] && [ -d /run/systemd/system ]; then
    systemctl disable --now minidns-adblock.timer minidns-zonesync.timer minidns-exporter.service 2>/dev/null || true
fi

exit 0
