// Package unbound generates the minidns unbound config fragment and talks
// to the running daemon via unbound-control.
package unbound

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/awkto/minidns/internal/config"
	"github.com/awkto/minidns/internal/paths"
)

// Render produces the full contents of /etc/unbound/unbound.conf.d/minidns.conf.
// Only RPZ/zone files that actually exist on disk are referenced, so a fresh
// install renders a valid config before any lists have been downloaded.
func Render(c *config.Config) string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	threads := c.Threads
	if threads <= 0 {
		threads = runtime.NumCPU()
	}

	w("# Generated by minidns — do not edit; run `minidns apply` after changing")
	w("# %s", paths.ConfigFile())
	w("server:")
	for _, iface := range c.Listen {
		w("  interface: %s", iface)
	}
	w("  port: %d", c.Port)
	for _, net := range c.AllowNetworks {
		w("  access-control: %s allow", net)
	}
	w("  chroot: \"\"")
	w("  username: unbound")
	w("  do-ip6: yes")
	w("  hide-identity: yes")
	w("  hide-version: yes")
	w("  qname-minimisation: yes")
	w("  harden-glue: yes")
	w("  harden-dnssec-stripped: yes")
	w("  aggressive-nsec: yes")
	w("")
	w("  # performance")
	w("  num-threads: %d", threads)
	w("  msg-cache-size: %dm", c.MsgCacheMB)
	w("  rrset-cache-size: %dm", c.RRsetCacheMB)
	w("  msg-cache-slabs: %d", slabs(threads))
	w("  rrset-cache-slabs: %d", slabs(threads))
	w("  infra-cache-slabs: %d", slabs(threads))
	w("  key-cache-slabs: %d", slabs(threads))
	w("  outgoing-range: 4096")
	w("  num-queries-per-thread: 2048")
	w("  so-reuseport: yes")
	w("  prefetch: yes")
	w("  prefetch-key: yes")
	w("")
	w("  # keep answering from cache when upstream/ISP is down")
	w("  serve-expired: yes")
	w("  serve-expired-ttl: 86400")
	w("")
	w("  # RPZ needs the respip module")
	w("  module-config: \"respip validator iterator\"")
	w("")
	if c.UpstreamTLS {
		if bundle := caBundle(); bundle != "" {
			w("")
			w("  # CA bundle to validate DoT upstream certificates")
			w("  tls-cert-bundle: %q", bundle)
		}
	}
	w("")
	w("  # statistics for `minidns stats` / the prometheus exporter")
	w("  extended-statistics: yes")
	w("  statistics-cumulative: no")

	if c.Logging.Queries {
		w("")
		w("  # query logging (epoch timestamps; `minidns logs` renders them)")
		w("  logfile: %q", paths.QueryLog())
		w("  log-time-ascii: no")
		w("  log-queries: yes")
		w("  log-replies: yes")
		w("  log-tag-queryreply: yes")
		w("  log-local-actions: yes")
		w("  val-log-level: 1")
	}

	// RPZ zones: first match wins across zones in config order, so the
	// allowlist comes first, then manual blocks, then adblock lists.
	rpz := func(name, file, tag string) {
		w("")
		w("rpz:")
		w("  name: %s", name)
		w("  zonefile: %q", file)
		w("  rpz-log: yes")
		w("  rpz-log-name: %s", tag)
	}
	if fileExists(paths.AllowRPZ()) {
		rpz("allow.rpz.minidns.", paths.AllowRPZ(), "allow")
	}
	if c.Firewall.Enabled && fileExists(paths.BlockRPZ()) {
		rpz("block.rpz.minidns.", paths.BlockRPZ(), "block")
	}
	if c.Adblock.Enabled {
		names := make([]string, 0, len(c.Adblock.Lists))
		for _, l := range c.Adblock.Lists {
			names = append(names, l.Name)
		}
		sort.Strings(names)
		for _, n := range names {
			if fileExists(paths.AdblockRPZ(n)) {
				rpz("adblock-"+n+".rpz.minidns.", paths.AdblockRPZ(n), "adblock-"+n)
			}
		}
	}

	// Local zone mirrors: answered from the on-disk copy, never upstream,
	// so they keep resolving through an ISP outage.
	for _, z := range c.Zones {
		if !fileExists(paths.ZoneFile(z.Name)) {
			continue
		}
		w("")
		w("auth-zone:")
		w("  name: %q", z.Name+".")
		w("  zonefile: %q", paths.ZoneFile(z.Name))
		w("  for-downstream: yes")
		w("  for-upstream: yes")
		w("  fallback-enabled: no")
	}

	if !c.Recursion && len(c.Upstreams) > 0 {
		w("")
		w("forward-zone:")
		w("  name: \".\"")
		if c.UpstreamTLS {
			w("  forward-tls-upstream: yes")
		}
		for _, u := range c.Upstreams {
			w("  forward-addr: %s", formatUpstream(u, c.UpstreamTLS))
		}
	}

	if !confDHasRemoteControl() {
		w("")
		w("remote-control:")
		w("  control-enable: yes")
		w("  control-interface: /run/unbound.control")
	}

	return b.String()
}

// slabs returns the power of two closest to (>=) the thread count, as the
// unbound docs recommend for the *-slabs options.
func slabs(threads int) int {
	s := 1
	for s < threads {
		s *= 2
	}
	return s
}

// formatUpstream renders a forward-addr. Config accepts "ip", "ip@port" or
// "ip@port#authname"; with TLS on, bare IPs get port 853 and a known auth
// name for the big public resolvers.
func formatUpstream(u string, tls bool) string {
	if !tls || strings.Contains(u, "@") {
		return u
	}
	authNames := map[string]string{
		"1.1.1.1": "cloudflare-dns.com", "1.0.0.1": "cloudflare-dns.com",
		"8.8.8.8": "dns.google", "8.8.4.4": "dns.google",
		"9.9.9.9": "dns.quad9.net", "149.112.112.112": "dns.quad9.net",
	}
	if name, ok := authNames[u]; ok {
		return u + "@853#" + name
	}
	return u + "@853"
}

// caBundle finds the system CA bundle for validating DoT upstream certs.
func caBundle() string {
	for _, p := range []string{
		"/etc/ssl/certs/ca-certificates.crt", // Debian/Ubuntu
		"/etc/pki/tls/certs/ca-bundle.crt",   // Fedora/RHEL
		"/etc/ssl/cert.pem",                  // Alpine/BSD
	} {
		if fileExists(p) {
			return p
		}
	}
	return ""
}

// confDHasRemoteControl reports whether another unbound.conf.d fragment
// (e.g. Debian's remote-control.conf) already enables remote control, so we
// don't emit a conflicting block.
func confDHasRemoteControl() bool {
	entries, err := filepath.Glob(filepath.Join(paths.UnboundConfD(), "*.conf"))
	if err != nil {
		return false
	}
	for _, f := range entries {
		if filepath.Base(f) == filepath.Base(paths.UnboundConfFile()) {
			continue
		}
		b, err := os.ReadFile(f)
		if err == nil && strings.Contains(string(b), "control-enable: yes") {
			return true
		}
	}
	return false
}

func fileExists(p string) bool {
	st, err := os.Stat(p)
	return err == nil && !st.IsDir()
}
