// Package unbound generates the minidns unbound config fragment and talks
// to the running daemon via unbound-control.
package unbound

import (
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/awkto/minidns/internal/config"
	"github.com/awkto/minidns/internal/paths"
)

// Render produces the full contents of /etc/unbound/unbound.conf.d/minidns.conf.
// Only RPZ/zone files that actually exist on disk are referenced, so a fresh
// install renders a valid config before any lists have been downloaded.
func Render(c *config.Config) string {
	var b strings.Builder
	w := func(format string, a ...any) { fmt.Fprintf(&b, format+"\n", a...) }

	threads := c.Threads
	if threads <= 0 {
		threads = runtime.NumCPU()
	}

	w("# Generated by minidns — do not edit; run `minidns apply` after changing")
	w("# %s", paths.ConfigFile())
	w("server:")
	for _, iface := range c.Listen {
		w("  interface: %s", iface)
	}
	w("  port: %d", c.Port)
	for _, net := range c.AllowNetworks {
		w("  access-control: %s allow", net)
	}
	w("  chroot: \"\"")
	w("  username: unbound")
	w("  do-ip6: yes")
	w("  hide-identity: yes")
	w("  hide-version: yes")
	w("  qname-minimisation: yes")
	w("  harden-glue: yes")
	w("  harden-dnssec-stripped: yes")
	w("  aggressive-nsec: yes")
	w("")
	w("  # performance")
	w("  num-threads: %d", threads)
	w("  msg-cache-size: %dm", c.MsgCacheMB)
	w("  rrset-cache-size: %dm", c.RRsetCacheMB)
	w("  msg-cache-slabs: %d", slabs(threads))
	w("  rrset-cache-slabs: %d", slabs(threads))
	w("  infra-cache-slabs: %d", slabs(threads))
	w("  key-cache-slabs: %d", slabs(threads))
	w("  outgoing-range: 4096")
	w("  num-queries-per-thread: 2048")
	w("  so-reuseport: yes")
	w("  prefetch: yes")
	w("  prefetch-key: yes")
	w("")
	w("  # keep answering from cache when upstream/ISP is down")
	w("  serve-expired: yes")
	w("  serve-expired-ttl: 86400")
	w("")
	w("  # RPZ needs the respip module")
	w("  module-config: \"respip validator iterator\"")
	w("")
	if usesTLS(c) {
		if bundle := caBundle(); bundle != "" {
			w("")
			w("  # CA bundle to validate DoT upstream certificates")
			w("  tls-cert-bundle: %q", bundle)
		}
	}
	w("")
	w("  # statistics for `minidns stats` / the prometheus exporter")
	w("  extended-statistics: yes")
	w("  statistics-cumulative: no")

	if c.Logging.Queries {
		w("")
		w("  # query logging (epoch timestamps; `minidns logs` renders them)")
		w("  logfile: %q", paths.QueryLog())
		w("  log-time-ascii: no")
		w("  log-queries: yes")
		w("  log-replies: yes")
		w("  log-tag-queryreply: yes")
		w("  log-local-actions: yes")
		w("  val-log-level: 1")
	}

	// Local authoritative zones. unbound ships built-in "static" local-zones
	// for private names (home.arpa, the RFC 1918 reverse trees, ...) that
	// would answer NXDOMAIN before the auth-zone is consulted, so each zone is
	// declared transparent; and a private name has no DNSSEC chain from the
	// root, so validation is switched off for exactly that subtree.
	local := localZones(c)
	if len(local) > 0 {
		w("")
		w("  # local authoritative zones")
		for _, z := range local {
			w("  local-zone: %q transparent", z+".")
			w("  domain-insecure: %q", z+".")
		}
	}

	if forwardsToLoopback(c) {
		w("")
		w("  # a forwarder on this host (e.g. a local DoH/DNSCrypt proxy)")
		w("  do-not-query-localhost: no")
	}

	// Zone forwarders need the same two exceptions: corp and RFC 1918 reverse
	// names are typically private, unsigned, and shadowed by built-in zones.
	if len(c.ZoneForwarders) > 0 {
		w("")
		w("  # zones forwarded to their own servers")
		for _, zf := range zoneForwarders(c) {
			w("  local-zone: %q transparent", zf.Zone+".")
			w("  domain-insecure: %q", zf.Zone+".")
		}
	}

	// RPZ zones: first match wins across zones in config order, so the
	// allowlist comes first, then manual blocks, then adblock lists.
	rpz := func(name, file, tag string) {
		w("")
		w("rpz:")
		w("  name: %s", name)
		w("  zonefile: %q", file)
		w("  rpz-log: yes")
		w("  rpz-log-name: %s", tag)
	}
	if fileExists(paths.AllowRPZ()) {
		rpz("allow.rpz.minidns.", paths.AllowRPZ(), "allow")
	}
	if c.Firewall.Enabled && fileExists(paths.BlockRPZ()) {
		rpz("block.rpz.minidns.", paths.BlockRPZ(), "block")
	}
	if c.Adblock.Enabled {
		names := make([]string, 0, len(c.Adblock.Lists))
		for _, l := range c.Adblock.Lists {
			if !l.Disabled {
				names = append(names, l.Name)
			}
		}
		sort.Strings(names)
		for _, n := range names {
			if fileExists(paths.AdblockRPZ(n)) {
				rpz("adblock-"+n+".rpz.minidns.", paths.AdblockRPZ(n), "adblock-"+n)
			}
		}
	}

	for _, z := range local {
		w("")
		w("auth-zone:")
		w("  name: %q", z+".")
		w("  zonefile: %q", paths.LocalZoneFile(z))
		w("  for-downstream: yes")
		w("  for-upstream: yes")
		w("  fallback-enabled: no")
	}

	// Cloud-zone replicas: answered from the on-disk copy, never upstream,
	// so they keep resolving through an ISP outage.
	for _, z := range c.CloudZones {
		if !fileExists(paths.ZoneFile(z.Name)) {
			continue
		}
		w("")
		w("auth-zone:")
		w("  name: %q", z.Name+".")
		w("  zonefile: %q", paths.ZoneFile(z.Name))
		w("  for-downstream: yes")
		w("  for-upstream: yes")
		w("  fallback-enabled: no")
	}

	if !c.Recursion && len(c.Upstreams) > 0 {
		w("")
		w("forward-zone:")
		w("  name: \".\"")
		if c.UpstreamTLS {
			w("  forward-tls-upstream: yes")
		}
		for _, u := range c.Upstreams {
			w("  forward-addr: %s", formatUpstream(u, c.UpstreamTLS))
		}
	}

	for _, zf := range zoneForwarders(c) {
		w("")
		w("forward-zone:")
		w("  name: %q", zf.Zone+".")
		if zf.TLS {
			w("  forward-tls-upstream: yes")
		}
		for _, u := range zf.Servers {
			w("  forward-addr: %s", formatUpstream(u, zf.TLS))
		}
	}

	if !confDHasRemoteControl() {
		w("")
		w("remote-control:")
		w("  control-enable: yes")
		w("  control-interface: /run/unbound.control")
	}

	return b.String()
}

func forwardsToLoopback(c *config.Config) bool {
	all := [][]string{}
	if !c.Recursion {
		all = append(all, c.Upstreams)
	}
	for _, zf := range c.ZoneForwarders {
		all = append(all, zf.Servers)
	}
	for _, list := range all {
		for _, u := range list {
			if f, err := config.ParseForwarder(u); err == nil && f.Addr.IsLoopback() {
				return true
			}
		}
	}
	return false
}

func usesTLS(c *config.Config) bool {
	for _, zf := range c.ZoneForwarders {
		if zf.TLS {
			return true
		}
	}
	return c.UpstreamTLS
}

// zoneForwarders returns the zone forwarders in a stable order.
func zoneForwarders(c *config.Config) []config.ZoneForwarder {
	out := append([]config.ZoneForwarder(nil), c.ZoneForwarders...)
	sort.Slice(out, func(i, j int) bool { return out[i].Zone < out[j].Zone })
	return out
}

// localZones returns the configured local zones that have a zone file, in
// a stable order.
func localZones(c *config.Config) []string {
	var out []string
	for _, z := range c.LocalZones {
		if fileExists(paths.LocalZoneFile(z)) {
			out = append(out, z)
		}
	}
	sort.Strings(out)
	return out
}

// slabs returns the power of two closest to (>=) the thread count, as the
// unbound docs recommend for the *-slabs options.
func slabs(threads int) int {
	s := 1
	for s < threads {
		s *= 2
	}
	return s
}

// formatUpstream renders a forward-addr. Config accepts "ip", "ip@port" or
// "ip@port#authname"; with TLS on, bare IPs get port 853 and a known auth
// name for the big public resolvers.
func formatUpstream(u string, tls bool) string {
	f, err := config.ParseForwarder(u)
	if err != nil || !tls {
		return u
	}
	authNames := map[string]string{
		"1.1.1.1": "cloudflare-dns.com", "1.0.0.1": "cloudflare-dns.com",
		"2606:4700:4700::1111": "cloudflare-dns.com", "2606:4700:4700::1001": "cloudflare-dns.com",
		"8.8.8.8": "dns.google", "8.8.4.4": "dns.google",
		"2001:4860:4860::8888": "dns.google", "2001:4860:4860::8844": "dns.google",
		"9.9.9.9": "dns.quad9.net", "149.112.112.112": "dns.quad9.net",
		"2620:fe::fe": "dns.quad9.net", "2620:fe::9": "dns.quad9.net",
	}
	if f.Port == 0 {
		f.Port = 853
	}
	if f.AuthName == "" {
		f.AuthName = authNames[f.Addr.String()]
	}
	return f.String()
}

// caBundlePaths are the places a system CA bundle may live.
var caBundlePaths = []string{
	"/etc/ssl/certs/ca-certificates.crt", // Debian/Ubuntu
	"/etc/pki/tls/certs/ca-bundle.crt",   // Fedora/RHEL
	"/etc/ssl/cert.pem",                  // Alpine/BSD
}

// caBundle finds the system CA bundle for validating DoT upstream certs.
func caBundle() string {
	for _, p := range caBundlePaths {
		if fileExists(p) {
			return p
		}
	}
	return ""
}

// confDHasRemoteControl reports whether another unbound.conf.d fragment
// (e.g. Debian's remote-control.conf) already enables remote control, so we
// don't emit a conflicting block.
func confDHasRemoteControl() bool {
	entries, err := filepath.Glob(filepath.Join(paths.UnboundConfD(), "*.conf"))
	if err != nil {
		return false
	}
	for _, f := range entries {
		if filepath.Base(f) == filepath.Base(paths.UnboundConfFile()) {
			continue
		}
		b, err := os.ReadFile(f)
		if err == nil && strings.Contains(string(b), "control-enable: yes") {
			return true
		}
	}
	return false
}

func fileExists(p string) bool {
	st, err := os.Stat(p)
	return err == nil && !st.IsDir()
}
