#!/bin/bash
# Rehearsal of upgrading a host shaped like pi.dnsif.ca (the first production
# install), on a disposable systemd VM — never on the real host:
#   v0.1.0 · Debian 12 · dnsif.ca replica via token_file · exporter on ·
#   adblock off · a foreign unbound fragment with PTR local-data next to ours.
#
#   sudo DIGITALOCEAN_TOKEN=... CANDIDATE=/tmp/minidns_X_amd64.deb bash upgrade-pi-shape.sh
set -uo pipefail
export DEBIAN_FRONTEND=noninteractive
: "${DIGITALOCEAN_TOKEN:?needs a token that can read the replicated zone}"
: "${CANDIDATE:?path to the candidate .deb}"
ZONE="${E2E_ZONE:-dnsif.ca}"; ZONE_HOST="${E2E_ZONE_HOST:-gitlab.dnsif.ca}"
ARCH="$(dpkg --print-architecture)"
PASS=0; FAIL=0
ok()  { PASS=$((PASS+1)); echo "PASS: $1"; }
bad() { FAIL=$((FAIL+1)); echo "FAIL: $1"; }
check()  { local d="$1"; shift; if "$@" >/tmp/out 2>&1; then ok "$d"; else bad "$d"; sed 's/^/    /' /tmp/out | head -15; fi; }
expect() { local d="$1" p="$2"; shift 2; "$@" >/tmp/out 2>&1; if grep -qE "$p" /tmp/out; then ok "$d"; else bad "$d (no /$p/)"; sed 's/^/    /' /tmp/out | head -15; fi; }
wait_dns() { for _ in $(seq 1 60); do minidns test localhost >/dev/null 2>&1 && return 0; sleep 0.5; done; echo "unbound did not come back"; return 1; }

echo "== build the Pi's shape on v0.1.0 =="
curl -fsSL -o /tmp/old.deb "https://github.com/awkto/minidns/releases/download/v0.1.0/minidns_0.1.0_${ARCH}.deb" || exit 1
apt-get install -y -qq /tmp/old.deb >/dev/null 2>&1 || apt-get install -y /tmp/old.deb
mkdir -p /etc/minidns
( umask 077; printf '%s' "$DIGITALOCEAN_TOKEN" > /etc/minidns/do.token )
cat > /etc/minidns/config.yaml <<CONF
listen:
    - 0.0.0.0
port: 53
allow_networks:
    - 127.0.0.0/8
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
upstreams:
    - 1.1.1.1
    - 1.0.0.1
upstream_tls: false
recursion: false
threads: 0
msg_cache_mb: 64
rrset_cache_mb: 128
firewall:
    enabled: true
adblock:
    enabled: false
    lists:
        - name: stevenblack
          url: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
          format: hosts
zones: []
providers:
    digitalocean:
        token: ""
        token_file: /etc/minidns/do.token
logging:
    queries: true
exporter:
    enabled: true
    listen: 0.0.0.0:9153
CONF
chmod 600 /etc/minidns/config.yaml
minidns setup 2>&1 | tail -2
wait_dns
minidns zone add "$ZONE" >/dev/null 2>&1; wait_dns
# what gen-reverse.py leaves next to our fragment on the real host
cat > /etc/unbound/unbound.conf.d/minidns-reverse.conf <<'CONF'
# Generated by gen-reverse.py — do not edit.
server:
  local-data: "51.11.33.10.in-addr.arpa. PTR gitlab.dnsif.ca."
  local-data: "3.0.33.10.in-addr.arpa. PTR pi.dnsif.ca."
CONF
systemctl restart unbound; wait_dns
expect "v0.1.0 is what runs"              "v0.1.0" minidns version
expect "before: replica answers"          "rcode +NOERROR" minidns test "$ZONE_HOST"
expect "before: foreign PTR answers"      "gitlab.dnsif.ca" minidns test 51.11.33.10.in-addr.arpa PTR
expect "before: exporter serves metrics"  "minidns_up 1" curl -s http://127.0.0.1:9153/metrics
cp /etc/unbound/unbound.conf.d/minidns.conf /tmp/minidns.conf.before
cp /etc/minidns/config.yaml /tmp/config.yaml.before
cp "/var/lib/minidns/zones/$ZONE.zone" /tmp/zone.before
UNBOUND_PID="$(systemctl show -p MainPID --value unbound)"

echo "== upgrade to $(basename "$CANDIDATE") =="
apt-get install -y "$CANDIDATE" 2>&1 | grep -E "minidns|WARNING" | sed 's/^/    /'
wait_dns

echo "== afterwards =="
check  "generated unbound config is byte-identical" cmp /tmp/minidns.conf.before /etc/unbound/unbound.conf.d/minidns.conf
expect "unbound was not restarted (same process, cache kept)" "^$UNBOUND_PID\$" systemctl show -p MainPID --value unbound
check  "original config kept as config.yaml.pre-v0.2" cmp /tmp/config.yaml.before /etc/minidns/config.yaml.pre-v0.2
expect "config.yaml migrated to cloud_zones"   "^cloud_zones:" cat /etc/minidns/config.yaml
check  "token_file setup left as it was"       grep -q "token_file: /etc/minidns/do.token" /etc/minidns/config.yaml
expect "a pre-migration backup exists"         "before-migration" minidns backup list
expect "replica answers"                       "rcode +NOERROR" minidns test "$ZONE_HOST"
expect "foreign PTR fragment still answers"    "gitlab.dnsif.ca" minidns test 51.11.33.10.in-addr.arpa PTR
check  "replica file format untouched (other tools parse it)" cmp /tmp/zone.before "/var/lib/minidns/zones/$ZONE.zone"
check  "zonesync unit runs with the new binary" systemctl start minidns-zonesync.service
check  "blocklist unit runs with the new binary" systemctl start minidns-adblock.service
expect "exporter still serves metrics"         "minidns_up 1" curl -s http://127.0.0.1:9153/metrics
expect "exporter unit active"                  "^active" systemctl is-active minidns-exporter.service
expect "cloud zone list"                       "$ZONE +digitalocean" minidns cloud zone list
expect "doctor: nothing failed"                " 0 failed" minidns doctor
expect "unbound still the same process after all of it" "^$UNBOUND_PID\$" systemctl show -p MainPID --value unbound

echo "== rollback to v0.1.0 (docs/ROLLOUT.md) =="
cp /etc/minidns/config.yaml.pre-v0.2 /etc/minidns/config.yaml
apt-get install -y --allow-downgrades /tmp/old.deb >/dev/null 2>&1
wait_dns
expect "v0.1.0 runs again"                     "v0.1.0" minidns version
expect "replica answers after rollback"        "rcode +NOERROR" minidns test "$ZONE_HOST"
expect "zone sync works after rollback"        "unchanged|updated" minidns zone sync
check  "unbound active"                        systemctl is-active --quiet unbound

echo; echo "RESULT: $PASS passed, $FAIL failed"
[ "$FAIL" -eq 0 ]
